### PR TITLE
Multiple fixes to bring TypeScript defs in line with API docs

### PR DESCRIPTION
**Pull request by shenningsgard**
Modified DOMContainerProperties.container to include Node type

(This more closely matches both the online documentation and API behavior: https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#container)

### CODE REVIEW

**Comment by jgravois** [comment]
very cool!

**Comment by shenningsgard** [comment]
I made an additional change, modifying the Collection class to be Generic, supporting the implicit typing as defined in the API docs:

"Collection is a generic object that stores an array of items of the **same type**." (from [api-reference/esri-core-Collection.html](https://developers.arcgis.com/javascript/latest/api-reference/esri-core-Collection.html))

**Comment by bsvensson** [comment]
Thank you @shenningsgard for your pull request.  The `arcgis-js-api.d.ts` file is actually being autogenerated from our source code, so we won't merge this PR for the generated file. However, we'll see if these changes can be incorporated into our source, and then make it into the autogenerated file.

**Comment by shenningsgard** [comment]
Thanks @bsvensson for taking a look! I assumed they were probably auto-generated, but I figured this might be a way to at least publicly propose changes for future revisions. We've had to carry through our modifications as we migrate to each point release, but on the whole the definitions have been getting better with each release.

If you don't mind me asking, is your source still in JavaScript, or have you moved to TypeScript?

**Comment by jgravois** [comment]
i remember a presentation where they said said new stuff was being written in TypeScript but my guess is that a 100% refactor is a lot lower priority than more feature completeness in `4.x`.

**Comment by bsvensson** [comment]
@shenningsgard @jgravois - Yes, some is in JavaScript, some is in TypeScript.

**Pull request closed without merging**
