### PR TITLE
feat: replace create-react-app with react with vite

### PR DESCRIPTION
**Pull request by odoe**
Need to create the tag for current state first before adding these updates.

### CODE REVIEW

**Comment by odoe** [comment]
I think I updated the metric scripts accordingly, I'm sure @benelan will tell me if I screwed it all up

**Comment by andygup** [comment]
I pushed a bunch of changes, here's the summary:
- Tweaked the analysis script so it will capture the new sample
- Made a few other minor updates to the analysis script
- Updated the @arcgis/core version to match other samples
- Tweaked vite.config.jsx

Looks like the CI mostly completed successfully. There's a node 12 deprecation warning that I'm looking into.

**Review by andygup — APPROVED** [review]
Looks like it's all working! I'll deal with the node.js warning in a separate PR.

**Comment by benelan** [comment]
Sorry I was OOO sick last week, but LGTM as well!

**Pull request merged**
