### PR TITLE
Addressing issue 19421

### PR DESCRIPTION
**Pull request by rrdlpl**
Addressing issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19421

### CODE REVIEW

**Comment by dasa** [comment]
Hi @rrdlpl, `items` isn't a supported property of `Collection`. Please use `toArray` or `getItemAt` instead.

Reference: https://developers.arcgis.com/javascript/latest/api-reference/esri-core-Collection.html

**Comment by rrdlpl** [comment]
@dasa I'm not using the layer object at all. This error appear when I do **ng build --prod**.

**Comment by dasa** [comment]
Can you update the code shown in the error message at the DT issue to not use `items`?

**Comment by rrdlpl** [comment]
I'm not sure what does DT mean. However, this is the component that is throwing the error. I didn't write it myself. It's a component from angular2-esri4-components. The angular2  version presents the same error too.

>  /node_modules/angular-esri-components/src/lib/widgets/layers-toggle/layers-toggle.component.d.ts.LayersToggleComponent.html (3,5): Property 'items' does not exist on type 'Collection'.

**layers-toggle.component.js**

```
import { Component, Input } from '@angular/core';
import { Esri4MapService } from './../../core/index';
export var LayersToggleComponent = (function () {
    function LayersToggleComponent(mapService) {
        this.mapService = mapService;
    }
    LayersToggleComponent.prototype.ngOnInit = function () {
        var _this = this;
        this.mapService.isLoaded.subscribe(function () {
            _this.map = _this.mapService.map;
            _this.mapView = _this.mapService.mapView;
        });
    };
    LayersToggleComponent.prototype.onCheck = function ($event, layer) {
        layer.visible = $event.target.checked;
    };
    LayersToggleComponent.prototype.onZoomLayer = function (layer) {
        this.mapView.goTo(layer.fullExtent);
    };
    LayersToggleComponent.decorators = [
        { type: Component, args: [{
                    selector: 'esri4-layersToggle',
                    template: "\n    <div esri4-customWidget [position]=\"position\">\n      <!-- Only display if there is a map and it has layers -->\n      <div *ngIf=\"map?.layers.items.length > 0\" class=\"esri4-layers-toggle\">\n        <div *ngFor=\"let layer of map.layers.items\">\n          <input type=\"checkbox\" [attr.checked]=\"layer.visible\" (click)=\"onCheck($event, layer)\" /> {{layer.title}}\n          <a href=\"javascript:void(0)\" (click)=\"onZoomLayer(layer)\">Zoom</a>\n        </div>\n      </div>\n    </div>\n  ",
                    styles: ["\n    .esri4-layers-toggle {\n      z-index: 99;\n      background-color: white;\n      border-radius: 8px;\n      padding: 10px;\n      opacity: 0.75;\n    }\n  "]
                },] },
    ];
    /** @nocollapse */
    LayersToggleComponent.ctorParameters = function () { return [
        { type: Esri4MapService, },
    ]; };
    LayersToggleComponent.propDecorators = {
        'position': [{ type: Input },],
    };
    return LayersToggleComponent;
}());
//# sourceMappingURL=layers-toggle.component.js.map

```

**Comment by dasa** [comment]
Sorry, DT was short for DefinitelyTyped. I'm not familiar with that component. Can you submit an Issue in that repo?

**Comment by rrdlpl** [comment]
ok thanks

**Pull request closed without merging**
